# Generated by Django 5.1.6 on 2025-03-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_alter_course_name'),
        ('trainee_app', '0002_alter_trainee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainees', to='course_app.course'),
        ),
    ]
